#!/usr/bin/env node
/**
 * Render the canonical site header into every page.
 *
 * The header was hand-maintained in twelve places: byte-identical across six marketing
 * pages, bespoke on /app, /director and /films, and a stub on privacy/terms. A new
 * feature landed in whichever copy you remembered, which is exactly how the Director
 * shipped visible from /app and /director and invisible from the other ten.
 *
 *   node build-nav.mjs           # rewrite the header in every page
 *   node build-nav.mjs --check   # fail if any page is stale (CI)
 *
 * Output is DETERMINISTIC — same menu in, same bytes out — which is what makes --check
 * meaningful rather than a daily false alarm.
 *
 * The generated block is scoped under the `gmn-` prefix and `.gmn`, deliberately NOT the
 * existing `gm-header`/`gm-nav` names: the marketing pages still ship those rules in
 * their own stylesheets, and reusing the names would have the two cascades fight.
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { MAIN } from "./nav/menu.mjs";

const CHECK = process.argv.includes("--check");
const START = "<!-- GMNAV:START — generated by build-nav.mjs; edit nav/menu.mjs instead -->";
const END = "<!-- GMNAV:END -->";

/* Pages that get the canonical header, and the path each one lives at (used to mark the
 * current section). admin/share/video-lab/geniemade-cyberhope are intentionally absent:
 * they are internal or standalone and do not carry the public bar. */
const ROOT_PAGES = [
  ["index.html", "/"],
  ["app.html", "/app"],
  ["director.html", "/director"],
  ["films.html", "/films"],
  ["account.html", "/account"],
  ["studio-you.html", "/studio-you"],
  ["studio-create.html", "/studio-you"],
  ["import.html", "/import"],
  ["verify.html", "/verify"],
  ["affiliates.html", "/affiliates"],
  ["privacy.html", "/privacy"],
  ["terms.html", "/terms"],
];

/* The occasion landing pages — 65 of them — are DISCOVERED, not listed. They were the
 * whole problem in miniature: they carry the old gm-header, so /invitations/wedding looked
 * like a different site, and a hand-written list here would go stale the first time someone
 * adds a new occasion. Anything matching these directories gets the canonical header
 * automatically, including pages that do not exist yet. */
const SECTION_DIRS = [
  ["invitations", "/invitations"],
  ["holidays", "/holidays"],
  ["make", "/make"],
  ["studio-you", "/studio-you"],
  ["people", "/people"],   // linked from the Studio menu, so it cannot be left on the old bar
  ["card", "/card"],
];
/* Deliberately excluded, and they should stay that way:
 *   c/           — the recipient's view of a card someone was sent. It is the delivered thing,
 *                  not a page of the site; it carries no site chrome and should not.
 *   share.html   — same reasoning.
 *   admin.html, video-lab.html, geniemade-cyberhope.html — internal. */

const PAGES = [...ROOT_PAGES];
for (const [dir, path] of SECTION_DIRS) {
  if (!existsSync(dir)) continue;
  for (const f of readdirSync(dir).filter((x) => x.endsWith(".html")).sort())
    PAGES.push([`${dir}/${f}`, path]);
}

const esc = (s) => String(s).replace(/&(?!#?\w+;)/g, "&amp;").replace(/</g, "&lt;");

/* One line, because the bar has to stay one line. The old /app header carried twelve
 * top-level items and wrapped onto a second row — which is what stretched "My Vault"
 * into a two-line button. Single words up top, detail in the dropdown. */
const CSS = `
/* position:sticky is defeated by a scrolling ancestor, and these pages set
 * \`body{overflow-x:hidden}\` — which makes body a scroll container, so the bar pinned itself to
 * a scrollport that never moves and simply scrolled away. Observed on /#pricing: the header sat
 * at rectTop -3411 with the page scrolled to 3411. \`clip\` suppresses horizontal overflow the
 * same way WITHOUT creating a scroll container, and html already uses clip here, so this matches
 * the pattern the site had already settled on. */
body{overflow-x:clip}

/* Defensive reset FIRST. Six of these pages still ship a bare \`header{...}\` element rule from
 * their old bespoke bar — films.html and verify.html set \`display:flex\` on it. A class beats an
 * element selector only for properties the class actually declares; anything left undeclared
 * still lands. Observed: /films rendered the new bar inset and centred instead of full-bleed.
 * So every property those rules touch is stated here explicitly. */
.gmn{display:block;width:100%;max-width:none;margin:0;padding:0;border:0;border-radius:0;float:none;
height:auto;min-height:0;align-items:initial;justify-content:initial;gap:0;flex:none;text-align:left}
.gmn{position:sticky;top:0;z-index:50;background:linear-gradient(180deg,rgba(19,10,38,.94),rgba(19,10,38,.72));
backdrop-filter:blur(10px);border-bottom:1px solid #3a2a6b;font:15px/1.4 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
.gmn *{box-sizing:border-box}
.gmn-bar{max-width:1320px;margin:0 auto;padding:10px 20px;display:flex;align-items:center;gap:6px}
.gmn-brand{display:flex;align-items:center;gap:9px;text-decoration:none;color:#f7f1ff;flex:0 0 auto;margin-right:6px}
.gmn-brand svg{width:26px;height:26px;filter:drop-shadow(0 3px 9px rgba(245,196,81,.45))}
.gmn-wm{font-family:ui-serif,Georgia,serif;font-size:1.18rem;font-weight:600;white-space:nowrap}
.gmn-wm b{color:#f5c451;font-weight:600}
.gmn-nav{display:flex;align-items:center;gap:2px;flex:1 1 auto;min-width:0}
.gmn-nav>a,.gmn-t{display:inline-flex;align-items:center;gap:4px;padding:8px 11px;border-radius:9px;
color:#d7cbf2;text-decoration:none;white-space:nowrap;font-size:15px;font-weight:600;letter-spacing:.005em}
.gmn-nav>a:hover,.gmn-t:hover{color:#f7f1ff;background:rgba(160,107,255,.14)}
.gmn-nav>a.on,.gmn-dd.on>.gmn-t{color:#f5c451}
.gmn-dd{position:relative}
.gmn-caret{font-size:10px;opacity:.7}
/* Anchored flush to the trigger, not 6px below it. That gap was a dead zone: the pointer left
 * .gmn-dd on the way down and the menu closed before it could be reached. The visual separation
 * now comes from the transparent ::before bridge, which is part of the hover area. */
.gmn-menu{position:absolute;top:100%;left:0;min-width:212px;padding:7px;margin-top:8px;
background:#1c1140;border:1px solid #3a2a6b;border-radius:12px;box-shadow:0 18px 40px rgba(0,0,0,.5);
display:none;flex-direction:column;gap:1px;max-height:min(70vh,520px);overflow-y:auto}
/* Bridge the 8px gap so travelling from the trigger down to the menu never leaves the hover
 * region. It has to hang off .gmn-dd, NOT off .gmn-menu: the menu is display:none until the
 * parent is hovered, so a bridge drawn on the menu disappears at the exact moment it is needed
 * and the menu shuts as the pointer enters the gap. Generated content counts as part of the
 * parent's box for hit-testing, so this keeps :hover continuous. */
.gmn-dd:hover::after,.gmn-dd:focus-within::after{content:"";position:absolute;top:100%;left:0;
right:-8px;height:12px}
.gmn-dd:hover>.gmn-menu,.gmn-dd:focus-within>.gmn-menu{display:flex}
.gmn-menu a{padding:8px 11px;border-radius:8px;color:#e9e0ff;text-decoration:none;font-size:14.5px;
font-weight:560;white-space:nowrap}
.gmn-menu a:hover{background:rgba(245,196,81,.14);color:#fff}
.gmn-right{display:flex;align-items:center;gap:8px;flex:0 0 auto}
.gmn-chip{font-size:13px;font-weight:600;color:#ffe390;border:1px solid #3a2a6b;border-radius:99px;padding:5px 11px;white-space:nowrap}
.gmn-btn{display:inline-flex;align-items:center;padding:7px 13px;border-radius:10px;border:1px solid #3a2a6b;
background:transparent;color:#f7f1ff;text-decoration:none;white-space:nowrap;font-size:14px;font-weight:600;cursor:pointer;font-family:inherit;
/* width/margin stated because verify.html ships \`button{width:100%;margin-top:16px}\` */
width:auto;margin:0;min-width:0;line-height:1.4}
.gmn-btn:hover{border-color:#f5c451}
.gmn-btn.gold{background:linear-gradient(180deg,#ffe390,#c88f2c);color:#2a1a05;border:0;font-weight:650}
.gmn-burger{display:none;margin:0 0 0 auto;background:none;border:1px solid #3a2a6b;border-radius:9px;
color:#f7f1ff;font-size:18px;padding:5px 11px;cursor:pointer;width:auto;font-family:inherit;line-height:1.4}
[hidden]{display:none !important}
@media(max-width:1080px){
  .gmn-burger{display:block}
  .gmn-nav{display:none;position:absolute;top:100%;left:0;right:0;flex-direction:column;align-items:stretch;
    background:#1c1140;border-bottom:1px solid #3a2a6b;padding:8px;gap:2px;max-height:78vh;overflow-y:auto}
  .gmn.open .gmn-nav{display:flex}
  .gmn-menu{position:static;display:flex;border:0;background:transparent;box-shadow:none;padding:0 0 4px 14px;max-height:none;margin-top:0}
  .gmn-dd:hover::after{display:none}
  .gmn-dd>.gmn-t{width:100%}
}
@media(max-width:560px){.gmn-chip,.gmn-signout{display:none}}
`.trim();

function renderNav(current) {
  const parts = [];
  for (const g of MAIN) {
    const active = current === g.href || (g.items || []).some(([h]) => h === current);
    if (!g.items) {
      parts.push(`<a href="${g.href}"${active ? ' class="on"' : ""}>${esc(g.label)}</a>`);
      continue;
    }
    parts.push(
      `<div class="gmn-dd${active ? " on" : ""}">` +
        `<a class="gmn-t" href="${g.href}">${esc(g.label)} <span class="gmn-caret">▾</span></a>` +
        `<div class="gmn-menu">` +
        g.items.map(([h, l]) => `<a href="${h}">${l}</a>`).join("") +
        `</div></div>`
    );
  }
  return parts.join("");
}

/* Signed-in and signed-out states are decided here, once, from /api/me — rather than by
 * each page rolling its own. #gmSignout, #creditN and #accountBtn keep their ids because
 * nine pages plus studio.js and director.js already drive them. */
const RUNTIME = `
(function(){
  var h=document.querySelector('.gmn'); if(!h) return;
  var b=h.querySelector('.gmn-burger');
  if(b) b.onclick=function(){h.classList.toggle('open')};
  fetch('/api/me',{credentials:'include'}).then(function(r){return r.ok?r.json():null}).then(function(d){
    var inn=!!(d&&d.ok), q=function(s){return h.querySelector(s)};
    h.querySelectorAll('[data-in]').forEach(function(el){el.hidden=!inn});
    h.querySelectorAll('[data-out]').forEach(function(el){el.hidden=inn});
    if(inn&&d.credits!=null){var c=q('#creditN'); if(c) c.textContent=d.credits;}
    // On /app, studio.js owns this button and assigns .onclick after us, so it wins there.
    // Everywhere else it would be an inert button, so give it somewhere to go.
    var a=q('#accountBtn');
    if(a){ if(inn&&(d.name||d.email)) a.textContent=d.name||d.email;
           if(!a.onclick) a.onclick=function(){location.href=inn?'/account':'/app';}; }
  }).catch(function(){});
})();`.trim();

function block(current) {
  return [
    START,
    `<style>${CSS}</style>`,
    `<header class="gmn">`,
    `<div class="gmn-bar">`,
    `<a class="gmn-brand" href="/"><svg viewBox="0 0 48 48" aria-hidden="true"><defs><linearGradient id="gmnlg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#ffe390"/><stop offset="1" stop-color="#e0a52f"/></linearGradient></defs><path d="M6 30c0-4 6-7 15-7 3 0 5 .3 7 .8l7-3.5c1.4-.7 2.6.9 1.7 2.2l-2.3 3.2c2 1.3 3.2 2.8 3.2 4.3 0 4-7 7-16.5 7S6 34 6 30Z" fill="url(#gmnlg)"/></svg><span class="gmn-wm">Genie<b>Made</b></span></a>`,
    `<button class="gmn-burger" aria-label="Menu">☰</button>`,
    `<nav class="gmn-nav" aria-label="Main navigation">${renderNav(current)}</nav>`,
    `<div class="gmn-right">`,
    `<span class="gmn-chip" id="gmnCredits" data-in hidden>✦ <span id="creditN">—</span> wishes</span>`,
    `<a class="gmn-btn" href="/app#vault" data-in hidden>Vault</a>`,
    `<a class="gmn-btn" href="/account" data-in hidden>Account</a>`,
    // Hidden by default and revealed by each marketing page's own script, exactly as before —
    // nine pages drive this id and none of them expect it visible until sign-in.
    `<a class="gmn-btn gmn-signout" id="gmSignout" href="#" style="display:none">Sign out</a>`,
    // The auth toggle. studio.js does `$("#accountBtn").onclick = ...` with no null guard, so it
    // has to EXIST on every page that might load studio.js — but it is only shown on /app, which
    // is the only place that drives it. It is NOT the Account link: studio.js rewrites its text to
    // the signed-in user's name, so merging the two made "Account" read "Sign in".
    `<button class="gmn-btn" id="accountBtn"${current === "/app" ? "" : " hidden"}>Sign in</button>`,
    `<a class="gmn-btn gold" href="/app" data-out>Open the Studio</a>`,
    `</div></div></header>`,
    `<script>${RUNTIME}</script>`,
    END,
  ].join("\n");
}

/* Replace whatever header the page currently has: a previously generated block, or the
 * hand-written <header>…</header> it still carries. */
function apply(html, current) {
  const want = block(current);
  const marked = new RegExp(`${START.replace(/[.*+?^${}()|[\]\\—]/g, "\\$&")}[\\s\\S]*?${END}`);
  if (marked.test(html)) return html.replace(marked, want);
  const hdr = html.match(/<header[\s\S]*?<\/header>/);
  if (hdr) return html.replace(hdr[0], want);
  return html.replace(/(<body[^>]*>)/i, `$1\n${want}`);
}

let stale = [];
for (const [file, path] of PAGES) {
  if (!existsSync(file)) { console.error(`missing ${file}`); process.exit(1); }
  const before = readFileSync(file, "utf8");
  const after = apply(before, path);
  if (before === after) continue;
  if (CHECK) stale.push(file);
  else writeFileSync(file, after);
}

if (CHECK) {
  if (stale.length) {
    console.error(`\nThe header is STALE in ${stale.length} page(s):\n  ${stale.join("\n  ")}\n\n` +
      `Someone edited a page header by hand, or changed nav/menu.mjs without rebuilding.\n\n` +
      `Fix:  node build-nav.mjs && git add -A\n`);
    process.exit(1);
  }
  console.log(`header is current in all ${PAGES.length} pages.`);
} else {
  console.log(`header written into ${PAGES.length} pages`);
  console.log(`  top level: ${MAIN.map((g) => g.label + (g.items ? "▾" : "")).join(" · ")}`);
}
